[theme]
base = "light"
# Puedes personalizar colores adicionales aqu√≠, ej:
primaryColor = "#F63366"
backgroundColor = "#FFFeee"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
